language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
script:
  npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GH_TOKEN
  on:
    branch: master
